<?php

namespace App\Filament\Resources\NewsResource\Pages;

use App\Filament\Resources\NewsResource;
use Filament\Actions;
use Filament\Resources\Pages\CreateRecord;

class CreateNews extends CreateRecord
{
    protected static string $resource = NewsResource::class;

    protected function mutateFormDataBeforeCreate(array $data): array
    {
        $data['user_id'] = auth()->id();
        if($data['publish_status']){
            $data['published_at'] = now();
        }
        return parent::mutateFormDataBeforeCreate($data); // TODO: Change the autogenerated stub
    }
}
